### ISSUE TITLE
Low quality of slovak stopwords

### ISSUE THREAD

**Issue by drndos** [stopwords-iso/stopwords-sk#1]
The set provided is low quality, contains invalid characters and english words.
Also does not include all the stopwords that it should.
Much better set is here:
 - http://text.fiit.stuba.sk/zoznam_stop_slov.php#focus
Above site provides explanation why words are chosen to be stopwords

I have compiled even better set carefully combining each stopwords source and adding my own stopwords that I found while developing NLP Tools for Slovak language (https://github.com/drndos/nlp-tools), that I would like to share and standardize.

**Comment by drndos** [comment]
I would like to remove these stopwords:

- a - I have no idea what that was supposed to be. We don't have that character in slovak language.
- and - This is English word
- buï - Bad character conversion should have been "buď"
- èi - Bad character conversion should have been "či"
- èí - Bad character conversion should have been "čí"
- èo - Bad character conversion should have been "čo"
- for - This is English word
- keï - Bad character conversion should have been "keď"
- kedže - this should be "keďže"
- menej - this is not supposed to be a stopword although it is common word it has big meaning
- mna - this should be "mňa"
- mòa - Bad character conversion should have been "mňa" - so duplicate
- nová  - this is not supposed to be a stopword although it is common word it has big meaning
- nové - this is not supposed to be a stopword although it is common word it has big meaning
- noví - this is not supposed to be a stopword although it is common word it has big meaning
- nový - this is not supposed to be a stopword although it is common word it has big meaning
- of - This is English word
- òom - Bad character conversion should have been "ňom"
- òou - Bad character conversion should have been "ňou"
- òu  - Bad character conversion should have been "ňu"
- prvá - this is not supposed to be a stopword although it is common word it has big meaning
- prvé - this is not supposed to be a stopword although it is common word it has big meaning
- prví - this is not supposed to be a stopword although it is common word it has big meaning
- prvý - this is not supposed to be a stopword although it is common word it has big meaning
- pýta - this is not supposed to be a stopword although it is common word it has big meaning
- te - Czech word
- tě - Czech word
- the - This is English word
- veï - Bad character conversion should have been "veď"

**Comment by genediazjr** [comment]
sorry for the very late response. thank you for your contribution! @drndos
